modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/jaquadro/HungerStrike/issues"
displayURL="https://minecraft.curseforge.com/projects/hungerstrike"
authors="Texelsaur"

[[mods]]
    modId="hungerstrike"
    version="${version}"
    displayName="Hunger Strike"
    description='''
    Restores pre-hunger health mechanics
    '''

[[dependencies.hungerstrike]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hungerstrike]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"