modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/jaquadro/HungerStrike/issues"
displayURL="https://minecraft.curseforge.com/projects/hungerstrike"
authors="Texelsaur"
license="MIT"

[[mods]]
    modId="hungerstrike"
    version="${file.jarVersion}"
    displayName="Hunger Strike"
    description='''
    Restores pre-hunger health mechanics
    '''

[[dependencies.hungerstrike]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hungerstrike]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"